png(file="reading_quantity_all.png",width=640,height=640)
#quartz(dpi=72)
plot(all~year, data=reading.quantity,ylim=c(0,20),xlab="연도",ylab="연간독서량(권)",type="p",pch=17)
lines(all~year, data=reading.quantity)
title(main="연간 독서량의 변화")
dev.off()
png(file="reading_quantity_sex.png",width=640,height=640)
plot(m~year, data=reading.quantity,ylim=c(0,20),xlab="연도",ylab="연간독서량(권)",type="p",pch=17,col="blue")
lines(m~year,data=reading.quantity,lty=1,col="blue")
points(f~year,data=reading.quantity,pch=17,col="red")
lines(f~year,data=reading.quantity,lty=1,col="red")
legend("topright",legend=c("남","녀"),lty=1,col=c("blue","red"))
title(main="성별 연간 독서량의 변화")
dev.off()
png(file="reading_quantity_age.png",width=640,height=640)
plot(reading.quantity$"20s"~year, data=reading.quantity,ylim=c(0,20),xlab="연도",ylab="연간독서량(권)",type="p",pch=17)
lines(reading.quantity$"20s"~year, data=reading.quantity,lty=1)
points(reading.quantity$"30s"~year, data=reading.quantity,lty=1,pch=17,col="blue")
lines(reading.quantity$"30s"~year, data=reading.quantity,lty=1,col="blue")
points(reading.quantity$"40s"~year, data=reading.quantity,pch=17,col="red")
lines(reading.quantity$"40s"~year, data=reading.quantity,lty=1,col="red")
points(reading.quantity$"50s"~year, data=reading.quantity,pch=17,col="magenta")
lines(reading.quantity$"50s"~year, data=reading.quantity,lty=1,col="magenta")
points(reading.quantity$"60.over"~year, data=reading.quantity,pch=17,col="grey")
lines(reading.quantity$"60.over"~year, data=reading.quantity,lty=1,col="grey")
legend("bottomleft",legend=c("20대 이하","30대","40대","50대(이상)","60대 이상"),lty=1,col=c("black","blue","red","magenta","grey"))
title(main="연령별 연간 독서량의 변화")
dev.off()
png(file="reading_quantity_education.png",width=640,height=640)
plot(under.middle~year, data=reading.quantity,ylim=c(0,20),xlab="연도",ylab="연간독서량(권)",type="p",pch=17)
lines(under.middle~year, data=reading.quantity,lty=1)
points(high.school~year, data=reading.quantity,pch=17,col="blue")
lines(high.school~year, data=reading.quantity,col="blue")
points(college~year, data=reading.quantity,pch=17,col="red")
lines(college~year, data=reading.quantity,col="red")
legend("center",legend=c("중졸 이하","고졸","대재 이상"), lty=1,col=c("black","blue","red"))
title(main="학력별 연간 독서량의 변화")
dev.off()
png(file="reading_quantity_region.png",width=640,height=640)
plot(metro~year, data=reading.quantity,ylim=c(0,20),xlab="연도",ylab="연간독서량(권)",type="p",pch=17)
lines(metro~year, data=reading.quantity,lty=1)
points(medium~year, data=reading.quantity,pch=17,col="blue")
lines(medium~year, data=reading.quantity,col="blue")
points(small~year, data=reading.quantity,pch=17,col="red")
lines(small~year, data=reading.quantity,col="red")
legend("bottom",legend=c("대도시","중소도시","읍면"), lty=1,col=c("black","blue","red"))
title(main="거주지 규모별 연간 독서량의 변화")
dev.off()
